name: Smoke test evaluation - 10 minutes, 5 trials
on: [push, pull_request, workflow_dispatch]
jobs:
  evaluate:
    uses: jon-bell/jqf/.github/workflows/evaluation-workflow.yml@reporting-ci
    with:
      duration: 10m
      trials: 5
      fuzzer_to_invoke: ./bin/confetti
      java_home: /usr/lib/jvm/jdk1.8.0_301/
    env:
      PROFILE_HEAP: true
